/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadgrupo36.Vistas;

import java.awt.Dimension;
import javax.swing.SwingUtilities;

/**
 *
 * @author marce
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        escritorio.setSize(1024, 720);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMAlumno = new javax.swing.JMenu();
        jMIFormularioalu = new javax.swing.JMenuItem();
        jMMateria = new javax.swing.JMenu();
        jMIFormularioMate = new javax.swing.JMenuItem();
        jMAdministracion = new javax.swing.JMenu();
        jMIManejoIns = new javax.swing.JMenuItem();
        jMIManipulaNota = new javax.swing.JMenuItem();
        JMConsultas = new javax.swing.JMenu();
        jMIAlumnosMate = new javax.swing.JMenuItem();
        jMSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Universidad de la punta");

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMAlumno.setText("Alumno");
        jMAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAlumnoActionPerformed(evt);
            }
        });

        jMIFormularioalu.setText("Formulario de Alumnos");
        jMIFormularioalu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIFormularioaluActionPerformed(evt);
            }
        });
        jMAlumno.add(jMIFormularioalu);

        jMenuBar1.add(jMAlumno);

        jMMateria.setText("Materia");

        jMIFormularioMate.setText("Formulario de Materia");
        jMIFormularioMate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIFormularioMateActionPerformed(evt);
            }
        });
        jMMateria.add(jMIFormularioMate);

        jMenuBar1.add(jMMateria);

        jMAdministracion.setText("Administracion");

        jMIManejoIns.setText("Manejo de Inscripciones");
        jMIManejoIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIManejoInsActionPerformed(evt);
            }
        });
        jMAdministracion.add(jMIManejoIns);

        jMIManipulaNota.setText("Manipulacion de Notas");
        jMIManipulaNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIManipulaNotaActionPerformed(evt);
            }
        });
        jMAdministracion.add(jMIManipulaNota);

        jMenuBar1.add(jMAdministracion);

        JMConsultas.setText("Consultas");

        jMIAlumnosMate.setText("Alumnos por Materia");
        jMIAlumnosMate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAlumnosMateActionPerformed(evt);
            }
        });
        JMConsultas.add(jMIAlumnosMate);

        jMenuBar1.add(JMConsultas);

        jMSalir.setText("Salir");
        jMSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSalirActionPerformed
        
    }//GEN-LAST:event_jMSalirActionPerformed

    private void jMIFormularioaluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIFormularioaluActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        AlumnoVista av=new AlumnoVista();
         Dimension desktopSize = escritorio.getSize();
            Dimension frameSize = av.getSize();
            
            int x = (desktopSize.width - frameSize.width) / 2;
            int y = (desktopSize.height - frameSize.height) / 2;
            av.setLocation(x, y);
        av.setVisible(true);
        escritorio.add(av);
    }//GEN-LAST:event_jMIFormularioaluActionPerformed

    private void jMIFormularioMateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIFormularioMateActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        MateriaVista m=new MateriaVista();
         Dimension desktopSize = escritorio.getSize();
            Dimension frameSize = m.getSize();
            
            int x = (desktopSize.width - frameSize.width) / 2;
            int y = (desktopSize.height - frameSize.height) / 2;
            m.setLocation(x, y);
        m.setVisible(true);
        escritorio.add(m);
        
    }//GEN-LAST:event_jMIFormularioMateActionPerformed

    private void jMIManejoInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIManejoInsActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        ManejoInscripcions mi=new ManejoInscripcions();
//         Inscripciones mi = new Inscripciones();
         Dimension desktopSize = escritorio.getSize();
            Dimension frameSize = mi.getSize();
            
            int x = (desktopSize.width - frameSize.width) / 2;
            int y = (desktopSize.height - frameSize.height) / 2;
            mi.setLocation(x, y);
        mi.setVisible(true);
        escritorio.add(mi);
    }//GEN-LAST:event_jMIManejoInsActionPerformed

    private void jMIManipulaNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIManipulaNotaActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        ManejoNota mn=new ManejoNota();
         Dimension desktopSize = escritorio.getSize();
            Dimension frameSize = mn.getSize();
            
            int x = (desktopSize.width - frameSize.width) / 2;
            int y = (desktopSize.height - frameSize.height) / 2;
            mn.setLocation(x, y);
        mn.setVisible(true);
        escritorio.add(mn);
    }//GEN-LAST:event_jMIManipulaNotaActionPerformed

    private void jMIAlumnosMateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAlumnosMateActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        AlumnosMaterias am=new AlumnosMaterias();

         Dimension desktopSize = escritorio.getSize();
            Dimension frameSize = am.getSize();
            
            int x = (desktopSize.width - frameSize.width) / 2;
            int y = (desktopSize.height - frameSize.height) / 2;
            am.setLocation(x, y);
        am.setVisible(true);
        escritorio.add(am);
    }//GEN-LAST:event_jMIAlumnosMateActionPerformed

    private void jMAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMConsultas;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMAdministracion;
    private javax.swing.JMenu jMAlumno;
    private javax.swing.JMenuItem jMIAlumnosMate;
    private javax.swing.JMenuItem jMIFormularioMate;
    private javax.swing.JMenuItem jMIFormularioalu;
    private javax.swing.JMenuItem jMIManejoIns;
    private javax.swing.JMenuItem jMIManipulaNota;
    private javax.swing.JMenu jMMateria;
    private javax.swing.JMenu jMSalir;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables



}
